midi.useRawSerial()
midi.playTone(880, music.beat(BeatFraction.Breve))
midi.playTone(MidiInstrument.Clavi, music.beat(BeatFraction.Whole))
midi.playTone(294, music.beat(BeatFraction.Whole))
midi.toneOn(262)
midi.toneOn(294)
music.rest(music.beat(BeatFraction.Half))
midi.toneOn(247)
midi.toneOff(294)
